version: '3'

volumes:
  fider_local_postgres_data: {}

services:
  fider:
    build:
      context: .
      dockerfile: Dockerfile
    image: fider_local
    container_name: fider_local
    depends_on:
      - postgres
      - mailhog
    environment:
      ENVIRONMENT: dev
      BASE_URL: http://127.0.0.1:8080/
      DATABASE_URL: postgres://fider:s0m3g00dp4ssw0rd@postgres:5432/fider?sslmode=disable
      JWT_SECRET: VERY_STRONG_SECRET_SHOULD_BE_USED_HERE
      EMAIL_NOREPLY: horuki@higachi.cc
      EMAIL_SMTP_HOST: mailhog
      EMAIL_SMTP_PORT: 1025
    ports:
      - "8080:3000"

  postgres:
    image: postgres:latest
    container_name: fider_local_postgres
    volumes:
      - fider_local_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: s0m3g00dp4ssw0rd
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    container_name: fider_local_mailhog
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"